project:
  type: website

website:
  title: "NFL Spread: 1978-2013"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - models.qmd
      - source.qmd
      
  sidebar:
    - id: Plots
      title: "Plots"
      style: "floating"
      background: "#ffffff"
      collapse-level: 4
      contents:
        - plot _0-3.qmd
        - plot _3.5-4.5.qmd
        - plot _5-7.qmd
        - plot _7_plus.qmd
    

format:
  html:
    color: #11C1FF
    css: styles.css
    toc: true



