---
title: "Point Spread: 3.5 to 4.5 points"
format: html
editor: source
execute: 
  echo: false
  warning: false
  message: false
---

```{r}
library(tidyverse)
library(rstanarm)
```

```{r}
# Data files
list_of_files <- list.files(path = "data",
                            recursive = TRUE,
                            pattern = "\\.csv$",
                            full.names = TRUE)  
```

```{r}
# Import data
x <- read_csv(list_of_files, id = "file_name", show_col_types = FALSE) |> 
  janitor::clean_names() |> 
  drop_na() |>
  mutate(date = as.Date(date, "%m/%d/%Y"),
         spread = abs(line)) |> 
  mutate(victory_margin = abs(home_score - visitor_score)) |> 
  select(date, home_team, visitor, home_score, visitor_score, line, spread, victory_margin) |> 
  rename(home = home_team)
```

```{r}
# summary(x)
```

```{r}
# Model
obj_fit <- stan_glm(data = x,
         formula = victory_margin ~ spread,
         family = gaussian,
         refresh = 0,
         seed = 9)
```

What is the expected mean margin of victory?

```{r}
# when the spread is between 3.5 and 4.5 points
obs_3.5_4.5 <- tibble(spread = seq(3.5, 4.5, 0.5))
```

```{r}
# when the spread is between 3.5 and 4.5 points
pp_3.5_4.5 <- posterior_epred(object = obj_fit, newdata = obs_3.5_4.5) |> 
  as_tibble() |> 
  rowwise() |> 
  mutate(avg_diff_point_3.5_4.5 = mean(c_across(`1`:`3`)))

```

```{r}
# when the spread is between 3.5 and 4.5 points
plot2 <- pp_3.5_4.5 |> 
  ggplot(aes(x = avg_diff_point_3.5_4.5)) +
    geom_histogram(aes(y = after_stat(count/sum(count))),
                   bins = 100) +
    labs(title = "Posterior for Expected mean NFL Margin of Victory when Absolute Point Spread \nis between 3.5 and 4.5 points",
         subtitle = "",
         x = "Margin of Victory (points)",
         y = "Probability",
         caption = "Source: Kaggle (NFL scores and betting data)") +
    scale_x_continuous(labels = scales::number_format()) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1))  +
    theme_classic()
```

```{r}
plot2
```
